---
title: "Merging Data Frames"
output: github_document
---

```{r libraries}
library(tidyverse)
library(readr)
library(dplyr)
library(skimr)
library(here)
```


```{r read_data, warning = FALSE, message = FALSE}
status <- read_csv(here("data/status.csv"))
results <- read_csv(here("data/results.csv"))
constructors <- read_csv(here("data/constructors.csv"))
drivers <- read_csv(here("data/drivers.csv"))
races <- read_csv(here("data/races.csv"))


```

```{r join_data, warning = FALSE}
res_con <- inner_join(constructors %>% select(-url), 
                     results)
colnames(res_con) [colnames(res_con) %in% c("name", "nationality") ] <- 
  c("constructorname", "constructornat")


res_con_driv <- inner_join(drivers %>% select(driverId, driverRef, surname),
                           res_con)
f1merged <- inner_join(races %>% select(raceId, year, round, name, date),
                       res_con_driv)

colnames(f1merged) [colnames(f1merged) == "name"] <- "racename"

write_csv(f1merged, here("data/f1merged.csv"))
```




```{r create_hybrid_era_version, warning = FALSE}
f1merged <- read_csv(here("data/f1merged.csv"), 
    na = "\\N")

write_csv(f1merged, here("data/f1merged.csv"))

f1merged_hybrid <- f1merged %>%
  filter(year %in% 2014:2020)

write_csv(f1merged_hybrid, here("data/f1merged_hybrid.csv"))
```


```{r merged_stops, message = FALSE}
stops <- read_csv(here("data/pit_stops.csv")) 

stops_drivers <- inner_join(drivers %>% select(driverId, driverRef, surname),
                           stops)
stops_merged <- inner_join(f1merged %>% select(-time, -milliseconds),
                           stops_drivers) %>%
  filter(year %in% 2014:2020)

write_csv(stops_merged, here("data/stops_merged.csv"))
```



