---
title: "Visualisations Used in Presentation"
output: github_document
---

```{r libraries-and-data , message = FALSE, echo = FALSE}
library(tidyverse)
library(readr)
library(dplyr)
library(skimr)
library(here)

f1merged <- read_csv(here("data/f1merged.csv"))
f1merged_hybrid <- read_csv(here("data/f1merged_hybrid.csv"))

key_teams <- c("Ferrari", 
               "McLaren",
               "Mercedes",
               "Red Bull",
               "Williams")

team_colours <- c("Mercedes" = "#00d2be",
                  "Red Bull" = "#0600ef",
                  "Ferrari" = "#dc0000",
                  "Racing Point" = "#F596C8",
                  "Force India" = "#f596c8",
                  "AlphaTauri" = "#ffffff",
                  "McLaren" = "#ff8700",
                  "Renault" = "#fff500",
                  "Williams" = "#0082fa",
                  "Toro Rosso" = "#469BFF",
                  "Lotus F1" = "#000000",
                  "Alfa Romeo" = "#960000",
                  "Sauber" = "#960000",
                  "Haas F1 Team" = "#787878")

key_team_colours <- c("Ferrari" = "#dc0000",
                       "McLaren" = "#ff8700",
                       "Mercedes" = "#00d2be",
                       "Red Bull" = "#0600ef",
                       "Williams" = "#0082fa")

key_team_colours_wins <- c("AlphaTauri" = "grey",
                           "Ferrari" = "#dc0000",
                           "Mercedes" = "#00d2be",
                           "Racing Point" = "#F596C8",
                           "Red Bull" = "#0600ef")

key_team_colours_darker <- c("Williams" = "#0065C3",
                           "Ferrari" = "#A20000",
                           "Mercedes" = "#00A595",
                           "Red Bull" = "#040090",
                           "McLaren" = "#BF6500")
```

## Dataset

### Wins Pie Chart
```{r race-wins-by-constructor, echo = FALSE}
f1merged_hybrid %>%
  filter(positionText == 1) %>%
count(constructorname, sort = TRUE) %>% 
  ggplot(aes(x = "",
             y = n,
             fill = constructorname)) +
  geom_bar(stat = "identity") + 
  coord_polar('y', start = 0) +
  scale_fill_manual(values = key_team_colours_wins) +
  labs(title = "Race Wins by Constructor",
       subtitle = "In the hybrid era (2014-2020)",
       fill = "Constructor") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x  = element_blank()) +
  theme_void() +
  annotate(geom = "text", x = "", y = 68,  label = "74%", 
           color = "white", size = 12, fontface = "bold") +     #Mercedes
  annotate(geom = "text", x = "", y = 18,  label = "<1%",  
           color = "white", size = 3.5, fontface = "bold") +    #Racing Point
  annotate(geom = "text", x = "", y = 11.5,  label = "12%", 
           color = "white", size = 5, fontface = "bold") +      #Red Bull
  annotate(geom = "text", x = "", y = 126, label = "12%", 
           color = "white", size = 5, fontface = "bold") +      #Ferrari
  annotate(geom = "text", x = "", y = 138,   label = "<1%",  
           color = "white", size = 3.5, fontface = "bold")      #Alpha Tauri
```

### Finishing Position by Constructor Distribution
```{r finishing-position-by-constructor, echo = FALSE, warning = FALSE}
f1merged_hybrid %>%
  filter(constructorname %in% key_teams) %>%
  ggplot(aes(x = position, y = constructorname,
             fill = constructorname,
             color = constructorname)) +
  geom_boxplot(alpha = 0.6) +
  scale_fill_manual(values = key_team_colours) +
  scale_color_manual(values = key_team_colours_darker) +
  scale_x_reverse() +
  scale_y_discrete(position = "right") +
  labs(title = "Finishing Position of F1 Car Constructors",
       x = "Finishing Position",
       y = "",
       subtitle = "In the hybrid era (2014-2020)") +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        
        #Creates road line effect
        panel.grid.major.y = element_line(linetype = "dashed", size = 2.5)) +
  
  #Finish Lines
  geom_vline(xintercept = 0, color = "black", size = 3) +
  geom_vline(xintercept = 0, color = "white", size = 3, linetype = "dashed") +
  
  #Constructor Labels
  annotate(geom = "label", x = 18, y = "Williams",  label = "Williams", 
           color = "#0082fa", size = 4) +
  annotate(geom = "label", x = 8, y = "Red Bull",  label = "Red Bull", 
           color = "#0600ef", size = 4) +
  annotate(geom = "label", x = 4.5, y = "Mercedes",  label = "Mercedes", 
           color = "#00d2be", size = 3.5) +
  annotate(geom = "label", x = 15, y = "McLaren",  label = "McLaren", 
           color = "#ff8700", size = 4) +
  annotate(geom = "label", x = 8, y = "Ferrari",  label = "Ferrari", 
           color = "#dc0000", size = 4)
```

## Speed

### Constructor's Average Speeds
```{r constructor-average-speeds, echo = FALSE}
f1merged_hybrid %>%
  filter(constructorname %in% key_teams) %>%
  drop_na() %>%
  summarise(constructorname,
            "avg_lap_time_min" = ((milliseconds/laps)/60000) %>% round(5)) %>%
  group_by(constructorname) %>%
  ggplot(aes(x = avg_lap_time_min, y = constructorname, 
             fill = constructorname,
             color = constructorname)) +
  geom_boxplot(alpha = 0.6, width = 0.7) +
  scale_x_reverse() +
  coord_cartesian(xlim = c(2.5,1)) +
  scale_fill_manual(values = key_team_colours) +
  scale_color_manual(values = key_team_colours_darker) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        
        #Creates road line effect
        panel.grid.major.y = element_line(linetype = "dashed", size = 2.5)) +
  
  labs(title = "Average Lap Time of Formula 1 Racers",
       x = "Lap Time (Minutes)",
       y = "Constructor",
       subtitle = "In the hybrid era (2014-2020)") +
  
  #Finish Line
  geom_vline(xintercept = 1, color = "black", size = 3) +
  geom_vline(xintercept = 1, color = "white", size = 3, linetype = "dashed") +
  
  #Constructor Labels
  annotate(geom = "label", x = 1.25, y = "Williams",  label = "Williams", 
           color = "#0082fa", size = 4) +
  annotate(geom = "label", x = 1.25, y = "Red Bull",  label = "Red Bull", 
           color = "#0600ef", size = 4) +
  annotate(geom = "label", x = 1.25, y = "Mercedes",  label = "Mercedes", 
           color = "#00d2be", size = 4) +
  annotate(geom = "label", x = 1.25, y = "McLaren",  label = "McLaren", 
           color = "#ff8700", size = 4) +
  annotate(geom = "label", x = 1.25, y = "Ferrari",  label = "Ferrari", 
           color = "#dc0000", size = 4)
```

### Average Lap Time vs Finishing Position

```{r lap-time-vs-finishing-position, echo = FALSE}
f1merged_hybrid %>%
  filter(constructorname %in% key_teams) %>%
  summarise(constructorname, 
            "avg_lap_time_min" = ((milliseconds/laps)/60000) %>% round(5),
            position) %>%
  drop_na() %>%
  ggplot(aes(x = avg_lap_time_min, y = position)) +
  scale_x_reverse() +
  scale_y_reverse() +
  geom_jitter(alpha = 0.5, color = "azure4") +
  geom_smooth(method = lm, formula = y ~ x, color = "black") +
  theme_minimal() +
  labs(title = "Effect of Speed on Finishing Position",
       x = "Average Lap Time (minutes)",
       y = "Finishing Position",
       subtitle = "In the hybrid era (2014-2020)")
```

## Qualifying

### Qualifying Position vs Finishing Position
```{r qualifying-vs-finishing, echo = FALSE}
f1merged_hybrid %>%
  filter(!is.na(position) & grid != 0) %>%
  ggplot(aes(x = grid, y = position, color = constructorname == "Mercedes")) +
  geom_jitter(alpha = 0.6) +
  geom_smooth(method = lm, colour = "black", formula = y ~ x) +
  theme_classic() +
  labs(x = "Qualifying Position",
       y = "Race Finishing Position",
       title = "Qualifying Position vs. Finishing Position",
       subtitle = "In the hybrid era (2014-2020)",
       color = "Constructor") +
  scale_color_manual(values = c("azure4","#00d2be")) +
  theme(legend.position = "none") +
  scale_y_reverse() +
  scale_x_reverse() +
  annotate(geom = "label", x = 7, y = 0, label = "Mercedes",
           color = "#00d2be", size = 4, alpha = 0.6) +
  annotate(geom = "label", x = 17, y = 1, label = "Other", 
           color = "azure4", size = 4)
```

## Qualifying vs Finishing - Top 5
```{r qualifying-vs-finishing-top-5, echo = FALSE}
f1merged_hybrid %>%
  filter(!is.na(position) & grid != 0 & grid <= 5) %>%
  ggplot(aes(x = grid, y = position, color = constructorname == "Mercedes")) +
  geom_jitter() +
  geom_smooth(method = lm,
              formula = y ~ x,
              colour = "black") +
  labs(x = "Qualifying Position",
       y = "Race Finishing Position",
       title = "Qualifying Position vs. Finishing Position (Top 5 Qualifiers)",
       subtitle = "In the hybrid era (2014-2020)") +
  theme(legend.position = "none") +
  scale_color_manual(values = c("azure4","#00d2be")) +
  annotate(geom = "label", x = 1, y = 18, label = "Mercedes", color = "#00d2be") +
  annotate(geom = "label", x = 0.88, y = 16.6, label = "Other", color = "azure4") +
  scale_x_reverse() +
  scale_y_reverse()
```

### Qualifying vs Finishing - Rest
```{r qualifying-vs-finishing-rest}
f1merged_hybrid %>%
  filter(!is.na(position) & grid > 5) %>%
  ggplot(aes(x = grid, y = position, color = constructorname == "Mercedes")) +
  geom_jitter() +
  geom_smooth(method = lm,
              formula = y ~ x,
              colour = "black") +
  labs(x = "Qualifying Position",
       y = "Race Finishing Position",
       title = "Qualifying Position vs. Finishing Position (Top 5 Qualifiers)",
       subtitle = "In the hybrid era (2014-2020)") +
  theme(legend.position = "none") +
  scale_color_manual(values = c("azure4","#00d2be")) +
  annotate(geom = "label", x = 7.5, y = 21, label = "Mercedes", 
           color = "#00d2be") +
  annotate(geom = "label", x = 7.1, y = 19.4, label = "Other", 
           color = "azure4") +
  scale_x_reverse() +
  scale_y_reverse()
```

### Summary Statistics

```{r poles_wins_summary_statistics, echo = FALSE} 
f1merged_hybrid %>%
  filter(position == 1) %>%
  count(constructorname) %>%
  rename(race_wins = n) %>%
  mutate(percent = (race_wins / sum(race_wins)) * 100)

f1merged_hybrid %>%
  filter(grid == 1) %>%
  count(constructorname) %>%
  rename(pole_positions = n) %>%
  mutate(percent = (pole_positions / sum(pole_positions)) * 100)

```


## Reliability

### Retirements vs Points 
```{r retirements-vs-points, echo = FALSE}

ret_season <- f1merged_hybrid %>%
  filter(constructorname %in% key_teams & positionText == "R") %>%
  group_by(year, constructorname) %>%
  count(constructorname) %>%
  summarise(retirements = n, .groups = "drop")

points_season <- f1merged_hybrid %>%
  filter(constructorname %in% key_teams) %>%
  group_by(year, constructorname) %>%
  summarise(total_points = sum(points), .groups = "drop")

inner_join(points_season, ret_season)%>%
  ggplot(aes(x = retirements, y = total_points, colour = constructorname)) +
  geom_point(size = 2.5) + 
  geom_smooth(method = "lm",
              formula = y ~ x,
              colour = "black",
              se = FALSE) +
  labs(x = "Retirements",
       y = "Total Championship Points",
       title = "Retirements vs Total Points",
       subtitle = "Per Season",
       colour = "Constructor") +
  scale_colour_manual(values = key_team_colours)
```

